## Catalog Applications
# key_to_catalog:
#    name: Name of Application
#    entry_classname: Max
# The default template entry should always be present !!
user_defined:
   name: User Defined Catalog (Template system)
   entry_classname: FieldEntry
template:
   name: Laboratory Catalog  (Template system)
   entry_classname: FieldEntry
ucum_units:
   name: Ucum units
   entry_classname: UcumEntry
treat:
   name: Treatment Catalog
   entry_classname: OpsEntry