## Catalog Applications
# key_to_catalog:
#    name: Name of Application
#    entry_classname: Max
# The default 'template' and 'user_defined' entry should always be present !!
user_defined:
   name: User Defined Catalog (Template system)
   entry_classname: FieldEntry
template:
   name: Laboratory Catalog  (Template system)
   entry_classname: FieldEntry
ucum_units:
   name: Ucum units
   entry_classname: UcumEntry
diagnosis:
   name: Diagnosis Catalog (ICD)
   entry_classname: IcdEntry
atc:
   name: ATC Catalog
   entry_classname: AtcEntry
ops:
   name: Treatment Catalog (OPS)
   entry_classname: OpsEntry
